#ifndef VERSION_H
#define VERSION_H

#define PROJECT_NAME "dperf"
#define PROJECT_VERSION "0.0.32"
#define PROJECT_VERSION_MAJOR @PROJECT_VERSION_MAJOR @
#define PROJECT_VERSION_MINOR @PROJECT_VERSION_MINOR @
#define PROJECT_VERSION_PATCH @PROJECT_VERSION_PATCH @

#endif // VERSION_H
